export const posts = [{
  "id": 1,
  "date": "2015-01-15T23:55:14",
  "date_gmt": "2015-01-15T23:55:14",
  "guid": {"rendered": "http:\/\/www.demowp.com\/?p=765"},
  "modified": "2015-09-29T17:41:05",
  "modified_gmt": "2015-09-29T17:41:05",
  "slug": "article-one",
  "status": "publish",
  "type": "post",
  "link": "https:\/\/demowp.com\/article-one\/",
  "title": {"rendered": "Article One"},
  "content": {
    "rendered": "<h1>Lorem ipsum</h1>",
    "protected": false
  },
  "excerpt": {"rendered": "", "protected": false},
  "author": 2,
  "featured_media": 1,
  "comment_status": "open",
  "ping_status": "closed",
  "sticky": false,
  "template": "",
  "format": "standard",
  "meta": [],
  "categories": [1, 2, 3],
  "tags": [],
}]
