/* auto-generated by NAPI-RS */
/* eslint-disable */
/** Engine + pinned third-party versions, for drift auditing. */
export declare function engineVersion(): string

/** Render markdown to HTML (synchronous). */
export declare function render(input: string, options?: RenderOptions | undefined | null): string

/** Render markdown to HTML off the main thread. */
export declare function renderAsync(input: string, options?: RenderOptions | undefined | null): Promise<string>

export interface RenderOptions {
  emoji?: boolean
  toc?: boolean
  slug?: boolean
  highlight?: boolean
  gfm?: boolean
  math?: boolean
  mdx?: boolean
  rawHtml?: boolean
  /** Accepted for API compatibility; the engine has no cache. */
  caching?: boolean
}

/**
 * Render many documents under the same options — across all cores on
 * native builds (order preserved). This is the highest-throughput path
 * for multi-document workloads.
 */
export declare function renderBatch(inputs: Array<string>, options?: RenderOptions | undefined | null): Array<string>

/** `renderBatch`, computed off the main thread. */
export declare function renderBatchAsync(inputs: Array<string>, options?: RenderOptions | undefined | null): Promise<Array<string>>

/** Parse markdown to mdast, returned as a JSON string. */
export declare function renderToMdast(input: string, options?: RenderOptions | undefined | null): string

/** Validate markdown: parse and run every enabled transform. */
export declare function validate(input: string, options?: RenderOptions | undefined | null): void
