export const media = {
  "id": 1,
  "date": "2015-09-28T23:56:29",
  "date_gmt": "2015-09-28T23:56:29",
  "guid": {"rendered": "https://raw.githubusercontent.com/jaredwray/writr/main/logo.png"},
  "modified": "2015-09-28T23:56:29",
  "modified_gmt": "2015-09-28T23:56:29",
  "slug": "article-one-image",
  "status": "inherit",
  "type": "attachment",
  "link": "https:\/\/demowp.com\/article-one\/article-one-image\/",
  "title": {"rendered": "Article One Image"},
  "author": 2,
  "comment_status": "open",
  "ping_status": "open",
  "template": "",
  "meta": [],
  "caption": {"rendered": ""},
  "alt_text": "Article One Image",
  "media_type": "image",
  "mime_type": "image\/png",
}
