// Hand-written inputs for the writr-acorn differential corpus. Each snippet
// is checked whole and, via prefixes, as every incomplete input markdown-rs
// can hand the parser while tokenizing. Cover every acorn / acorn-jsx
// branch reachable from MDX: valid syntax, each early error, and each
// tokenizer error.
const r = String.raw;
/** `%uXXXX` → a literal `\uXXXX` escape in the source text. */
const u = (text) => text.replaceAll("%u", `${String.fromCharCode(92)}u`);

export const expressions = [
	// Numbers
	"1", "1.5", ".5", "1e10", "1E+5", "1e-5", "0x1F", "0X1f", "0o17", "0O7", "0b101", "0B1",
	"1_000_000", "1__0", "1_", "0_1", "0x_1", "0x1_f", "08", "07", "0", "00", "09.5", "1n",
	"0x1n", "0b1n", "0o7n", "1.5n", "1e3n", "0n", "01n", "1a", "3in x", ".e1", "1.", "1..toString()",
	"5.toString()", "0xg", "0b2", "0o8", "1e", "1e+", "1_e1", "1e1_0", "1.0_1", "._1", "0.0",
	"1 ", "0x", "0b", "0o", "123abc", "1\\u0061",
	// Strings
	'"a"', "'b'", r`"\n\t\\\"\'"`, r`"\x41"`, r`"\x4"`, r`"\u0041"`, r`"\u{41}"`, r`"\u{110000}"`,
	r`"\u{}"`, r`"\u{41"`, r`"\u00"`, r`"\0"`, r`"\00"`, r`"\01"`, r`"\8"`, r`"\9"`, r`"\7"`,
	r`"\377"`, r`"\400"`, '"a\\\nb"', '"a\\\r\nb"', '"a b"', '"a\\ b"', '"unterminated',
	'"line\nbreak"', "'mixed\"", r`"\uD83D\uDE00"`, '"😀"', r`"\c"`, r`"\0a"`, r`"\08"`, r`"\u{10FFFF}"`,
	r`"\u{0000041}"`, "'", '"', r`"\"`, r`"\u"`, r`"\x"`,
	// Templates
	"`a`", "`a${b}c`", "`${a}${b}`", "`\\u{41}`", "`\\unicode`", "tag`\\unicode`", "`\\01`",
	"`\\0`", "`${", "`", "`a", "`${a", "`${a}", "`${a}`", "`a\nb`", "`a\r\nb`", "`\\``", "`\\${`",
	"`${`a`}`", "`$`", "`${}`", "`${{}}`", "a`b${c}d`", "a`\\u{`", "`\\u{`", "`\\8`", "`\\",
	"`\\x4`",
	// Identifiers and keywords
	"a", "$", "_", "ä", r`\u0061`, r`\u{61}`, r`a\u0062`, r`\u0030`, r`\uD800`, "𝒜", "a𝒜", "x‌",
	"await", "yield", "let", "static", "implements", "enum", "eval", "arguments", "undefined",
	r`\u0069f`, r`\u{76}ar`, "in", "class", "function", "this", "super", "new.target",
	"import.meta", "null", "true", "false", r`n\u0065w A`, r`\u0074his`, r`\u0074rue`, "async",
	"of", "get", "set", "target", "meta", "a\\", "a\\u", "a\\u{", "a\\x41", "\\", "\\u", "\\u{",
	r`\u{1D49C}`, r`\u{110000}`, "a b", "a;", "a;b",
	// Operators
	"a + b", "a - b * c", "a ** b ** c", "-a ** b", "(-a) ** b", "a ?? b", "a ?? b || c",
	"a || b ?? c", "(a || b) ?? c", "a && b || c", "a | b ^ c & d", "a << b >> c >>> d",
	"a == b != c === d !== e", "a < b > c <= d >= e", "a instanceof b", "a in b", "!a", "~a", "+a",
	"-a", "typeof a", "void 0", "delete a", "delete a.b", "delete (a)", "delete a[b]", "++a", "a++",
	"--a", "a--", "++a++", "a\n++b", "1++", "++1", "a = b", "a += b", "a -= 1", "a **= 2",
	"a &&= b", "a ||= b", "a ??= b", "a >>>= 1", "a <<= 1", "a >>= 1", "a %= 1", "a /= 2", "a |= 1",
	"a ^= 1", "a &= 1", "1 = a", "a + b = c", "(a) = 1", "(a.b) = 1", "((a)) = 1", "[a, b] = c",
	"({a} = b)", "({a: 1} = b)", "[...a, b] = c", "[...a] = b", "a ? b : c", "a ? b", "a ?", "a, b, c",
	"(a, b)", "()", "(a,)", "(...a)", "a ? b : c ? d : e", "a?.b ? c : d", "a ?.5 : 1", "a?.5:1",
	"x = y = z", "a += b += c", "a.b++", "a?.b++", "(a?.b) = 1", "a?.b = 1", "[a?.b] = c",
	"({a: b?.c} = d)", "++a?.b", "delete a?.b", "a?.b.c", "a?.b?.c", "a!", "a!b", "a ! b",
	"a => a", "(a, b) => a + b", "(a = 1, {b}, [c], ...d) => 0", "async a => a", "async (a) => a",
	"async () => await a", "async\n() => a", "async\na => a", "(a, a) => 1", "(eval) => 1",
	"(arguments) => 1", "({a}) => a", "([a]) => a", "(a, ...b,) => 1", "(...a,) => 1", "() => {}",
	"() => ({})", "() => { return 1 }", 'x => { "use strict"; }', '(a = 1) => { "use strict" }',
	'({a}) => { "use strict" }', "() =>\n1", "()\n=> 1", "a\n=> 1", "(a) => (b) => c",
	"async (a, a) => 1", "async (await) => 1", "async () => { await }", "async (x = await 1) => x",
	"(x = yield) => x", "(x = await 1) => x", "(await a) => 1", "async await => 1",
	"async function f() {}", "function* g() { yield 1 }", "function* g() { yield* h() }",
	"function* g() { yield\n1 }", "function* g() { yield }", "function* g() { var yield }",
	"async function* f() { for await (x of y) {} }", "function f(a, a) {}", "function f() { return }",
	"function () {}", "(function f() {})", "function f(eval) {}", "function eval() {}",
	"function f(a = await b) {}", "async function f(a = await b) {}", "function* f(a = yield) {}",
	"function f() { 'use strict'; }", "function f(a = 1) { 'use strict'; }", "function f() { new.target }",
	"function f() { super.x }", "async function await() {}", "function* yield() {}",
	"async function f() { var await }", "async function f() { let [await] = a }",
	"class A {}", "class extends B {}", "class A extends B { constructor() { super() } }",
	"class A { constructor() { super() } }", "class A { #x; m() { return this.#x } }",
	"class A { m() { this.#y } }", "class A { static #x = 1; static { this.#x } }",
	"class A { get x() {} set x(v) {} }", "class A { get x(a) {} }", "class A { set x() {} }",
	"class A { set x(...a) {} }", "class A { constructor() {} constructor() {} }",
	"class A { static prototype() {} }", "class A { static prototype = 1 }", "class A { constructor = 1 }",
	"class A { #constructor() {} }", "class A { #a; #a }", "class A { get #a() {} set #a(v) {} }",
	"class A { static get #a() {} set #a(v) {} }", "class A { async *gen() {} }",
	"class A { static async *[Symbol.iterator]() {} }", "class A { 'constructor'() {} }",
	'class A { ["constructor"]() {} }', "class A { static; get; set; async; }",
	"class A { static static() {} }", "class A { x = arguments }", "class A { static { await } }",
	"class A { static { return } }", "class A { static { arguments } }", "class A { get constructor() {} }",
	"class A { async constructor() {} }", "class A { *constructor() {} }", "class A { static constructor() {} }",
	"class A { x = 1; y }", "class A { x = 1 y = 2 }", "class A { 'a' = 1; 2 = 3; [a] = b }",
	"class A { #a; m() { delete this.#a } }", "class A { #a; m() { #a in this } }",
	"class A { #a; m() { #b in this } }", "class A { m() { #a } }", "#a in b",
	"class A { static async\nx() {} }", "class A { async\nx() {} }", "class A { get\nx() {} }",
	"class A { static\nx() {} }", "class A { m() { super.m() } }", "class A { m() { super() } }",
	"class A { constructor() { new.target } }", "class A { x = super.y }", "class A { x = new.target }",
	"class A { x = () => arguments }", "class A extends B { x = super() }", "class { }", "class",
	"class A extends", "class A { ; }", "class A { static {} }", "class A { static { var a; let b; } }",
	"class A { m(a, a) {} }", "class A { m() { let a; var a } }", "class A { #a() {} get #a() {} }",
	"class A { static #a() {} #a }", "class A { get #a() {} static set #a(v) {} }",
	"class A { x; #y = this.#x }", "class A { #x = 1; static m(o) { return #x in o } }",
	"class A { a() {} class() {} if() {} }", "class A { 1() {} 'x'() {} }",
	"class A { static prototype }", "class A { static 'prototype'() {} }", "class A extends (B, C) {}",
	"class A extends B.C {}", "class A extends B() {}", "class A extends async () => {} {}",
	// Objects
	"{}", "({})", "({a})", "({a: 1, b})", "({a, b} = c)", "({a = 1})", "({a = 1} = b)", "({...a})",
	"({...a, b})", "({get a() {}, set a(v) {}})", "({get() {}})", "({async a() {}})", "({async *a() {}})",
	"({*a() {}})", "({a() {}})", '({"a": 1, 1: 2, [c]: 3})', "({__proto__: a, __proto__: b})",
	'({__proto__: a, "__proto__": b})', "({__proto__: a, __proto__})", "({__proto__: a, __proto__() {}})",
	"({__proto__: a, ['__proto__']: b})", "({async: 1})", "({async})", "({get: 1})", "({await})",
	"({if: 1})", "({if})", "({a b})", "({a,})", "({,})", "({a: 1,,})", "({get a(b) {}})",
	"({set a() {}})", "({set a(...b) {}})", "({get [a]() {}})", "({async get a() {}})", "({get *a() {}})",
	"({async\na() {}})", "({a: 1} = 1)", "({a: b.c} = d)", "({a: b()} = d)", "({...a} = b)",
	"({...a, b} = c)", "({...[a]} = b)", "({...{a}} = b)", "({...a,} = b)", "({a = 1, b: c = 2} = d)",
	"({__proto__: a, __proto__: b} = c)", "({a: (b)} = c)", "({a: (b.c)} = d)", "({(a)} = b)",
	"({a: 1}.a)", "({a}.b = c)", "({eval} = a)", "({arguments} = a)", "({if: a} = b)",
	"({yield})", "({let})", "({static})", "({implements})", "({1: a})", "({0x1: a, 1n: b})",
	"({a: 1, a: 2})", "({get a() {}, get a() {}})", "({a, a} = b)", "(a, {b}) => 1",
	// Arrays
	"[]", "[1, 2]", "[, a]", "[a, , b]", "[...a]", "[a,]", "[...a,]", "[...a, ...b]", "[,]", "[,,]",
	"[a = 1] = b", "[a = 1]", "[[a], {b}] = c", "[a.b] = c", "[a()] = b", "[...a = 1] = b",
	"[(a)] = b", "[(a = 1)] = b", "[...(a)] = b", "[...(a, b)] = c",
	// Calls and members
	"a.b", "a?.b", "a?.[b]", "a?.()", "a.b.c()", "a[b]", "a()", "a(...b)", "a(b,)", "a(,)", "new A",
	"new A()", "new A.b()", "new (a())()", "new a?.b()", "new import('x')", "import('x')",
	"import('x',)", "import('x', 'y')", "import()", "import.meta", "import.meta.url", "import.foo",
	"new.target", "new.foo", "a?.b`c`", "a`b`", "super.x", "this", "a\n.b", "a.#b", "a?.#b",
	"a.if", "a?.if", "a.class.b", "a.function", "a[b]()", "a(b)(c)", "new new A()()", "new A`b`",
	"new A?.()", "async(a)", "async(a)\n=> 1", "async (...a) => a", "async (a = await 1) => a",
	"a.b.c.d.e.f", "a(b, c, ...d, e)", "a(...b,)", "import(...a)", "import", "import.", "import.m",
	r`import.m\u0065ta`, r`new.t\u0061rget`, "(a, b) => {}; x", "f(a => b, c => d)",
	// Regular expressions
	"/a/", "/a/g", "/a/gimsuyd", "/a/v", "/a/uv", "/a/gg", "/a/x", "/[/]/", r`/\//`, "/a",
	"/a\n/", r`/(a)\1/`, r`/\1(a)/`, r`/(?<n>a)\k<n>/`, r`/(?<n>a)\k<m>/`, r`/\k<a>/`, r`/\k<a>/u`,
	"/(?<a>.)(?<a>.)/", "/(?<a>.)|(?<a>.)/", r`/\p{L}/u`, r`/\p{Letter}/u`, r`/\p{Script=Greek}/u`,
	r`/\p{sc=Grek}/u`, r`/\p{Foo}/u`, r`/\p{L}/`, r`/\P{RGI_Emoji}/v`, r`/\p{RGI_Emoji}/v`,
	r`/[\p{RGI_Emoji}--\q{x}]/v`, "/[a&&b]/v", "/[a--b]/v", "/[a&&&b]/v", "/[(]/v", "/[[a]]/v",
	r`/[^\q{ab}]/v`, "/a{2,1}/", "/a{2}/", "/a{,2}/", "/a{2,}/u", "/{/", "/{/u", "/}/", "/]/",
	"/]/u", "/)/", "/(?:a)/", "/(?=a)*/", "/(?=a)*/u", "/(?<=a)*/", r`/\c/`, r`/\cA/`, r`/[\c]/`,
	r`/[\c_]/`, r`/\u{1F600}/u`, r`/\u{110000}/u`, r`/\uD83D\uDE00/u`, r`/[\d-z]/`, r`/[\d-z]/u`,
	"/[z-a]/", r`/\x4/`, r`/\x4/u`, r`/\8/`, r`/\8/u`, r`/\00/`, r`/[\b]/`, r`/\B\b/`, "/^$/",
	"/a|b|/", "/(/", "/(?/", "/(?:/", "/a**/", "/a++/", "/a??/", "/.*?/", r`/\-/u`, r`/[\-]/u`,
	r`/\w\W\d\D\s\S/`, "/[^]/", "/[]/", r`/\q/`, r`/\q/u`, r`/[\q{a}]/v`, r`/\p{General_Category=Lu}/u`,
	r`/\p{gc=Xx}/u`, r`/\p{Scx=Latn}/u`, r`/\p{Script_Extensions=Latin}/u`, r`/\p{ASCII}/u`,
	r`/\p{Basic_Emoji}/u`, r`/\p{Basic_Emoji}/v`, r`/\p{}/u`, r`/\p/u`, r`/\p{L/u`, "/(?<a>)/",
	"/(?<>)/", "/(?<1>)/", r`/(?<\u0061>)/`, r`/(?<a\u{62}>)/`, "/(?<𝒜>)/", "/(?i:a)/", "/(?-i:a)/",
	"/a/ ", "/=a/", "a /= 2", "a / b / c", "(a) / b", "a\n/b/g", "x = /[/", r`/[\]/`, r`/\]/`,
	r`/[a-\d]/`, r`/[a-\d]/u`, r`/[\s-\d]/`, "/[a-]/", "/[-a]/", r`/\0/u`, r`/\01/u`, r`/[\01]/u`,
	r`/[\c1]/`, r`/\c1/`, r`/\c1/u`, r`/\u{41}/`, r`/\u{41/u`, r`/\uD83D/u`, r`/[\uD83D\uDE00-\uD83D\uDE02]/u`,
	"/[😀-😂]/", "/[😀-😂]/u", r`/\k/`, r`/\k/u`, r`/(?<a>)\k/`, r`/(?<a>)\k<a/`, "/a{1/", "/a{1/u",
	"/a{1,2/u", "/a{99999999999999999999,1}/", "/a{1,99999999999999999999}/", r`/\99999999999999999999/u`,
	r`/(a)\2/u`, r`/(a)\1/u`, "/(?!a)+/", "/(?<!a)+/", "/(?<=a)/", "/^*/", "/$+/", r`/\b*/`,
	r`/\B+/u`, "/[/]/v", r`/[\q{a|bc|}]/v`, r`/[\q{}]/v`, "/[a-z&&b]/v", "/[a&&]/v", "/[&&a]/v",
	"/[a--]/v", "/[!!]/v", "/[!]/v", "/[a!!b]/v", r`/[\!]/v`, r`/[\&]/v`, r`/[\b]/v`, r`/[\q]/v`,
	"/[[a]--[b]]/v", "/[^[a]]/v", r`/[^\p{RGI_Emoji}]/v`, r`/[\p{L}--[a-z]]/v`, "/[a-z--[aeiou]]/v",
	"/[\\d&&\\w]/v", "/(?:)/", "/a(?:b|c)*d/", "/(a(b(c(d))))/", "/(?:(?:(?:a)))/",
	// JSX
	"<a/>", "<a />", "<a></a>", "<a>text</a>", "<a>{b}</a>", "<a>{}</a>", "<a>{/* c */}</a>",
	"<a b=\"c\" d='e' f={g} {...h} i />", "<a b={} />", "<a b=c />", "<a:b />", "<a:b.c />",
	"<a.b.c />", "<a-b-c />", "<A.B></A.B>", "<A.B></A.C>", "<a></b>", "<></>", "<>text</>", "<></a>",
	"<a></>", "<a>&amp;&#123;&#x7B;&nope;</a>", "<a>></a>", "<a>}</a>", "<a>\n</a>",
	"<a><b /><c /></a>", "<a /><b />", "<a b=\"\n\" />", "<a b=\"unterminated />", "<a {...b, c} />",
	"<a {b} />", "<a>{a}{b}</a>", "<a>{() => <b />}</a>", "<this />", "<class />", r`<\u0061 />`,
	"<a b=<c /> />", "<a b=\"&quot;\" />", "<a>", "<a", "<a b", "<a b=", "<a>text", "<a>{", "<!--x-->",
	"< a />", "<a / >", "<a>< /a>", "<a></ a>", "<a:b:c />", "<a:b></a:b>", "<a:b></a:c>",
	"<a b:c=\"d\" />", "<a.b:c />", "<a b=\"c\"d />", "<a b='c'/>", "<a>{...b}</a>", "<a>{a, b}</a>",
	"<a>{a b}</a>", "<a {...b} />", "<a {...} />", "<a {...b /}", "<a b={c} d={e} />", "<a>😀</a>",
	"<a𝒜 />", "<𝒜 />", "<a-/>", "<-a />", "<a b-c=\"d\" />", "<a b={<c>{d}</c>} />", "<a>\r\n</a>",
	"<a>&</a>", "<a>&amp</a>", "<a>&#;</a>", "<a>&#x;</a>", "<a>&#xZZ;</a>", "<a>&toString;</a>",
	"<a b=\"&\" />", "<a>{'}'}</a>", "<a>{\"{\"}</a>", "<a>{`}`}</a>", "<a>{/* } */}</a>",
	"<a>{// }\n}</a>", "<a></a>< b />", "<a></a><b />", "<a></a> < b", "(<a />)", "[<a />, <b />]",
	"<a /> + 1", "<a></a>.b", "x ? <a /> : <b />", "<a key={1} {...b} c=\"d\">{e}</a>",
	"<a>{</a>", "<a>{a</a>", "<a>{a}</a", "<a>{a}</", "<a>{a}<", "<a b=\"c\">", "<a/ >", "<a/", "<a /",
	"<a b=\"c\" / >", "<a\n b\n/>", "<a b='\n'/>", "<a b=`c` />", "<a b=1 />", "<a b={1}c />",
	"<a if />", "<a if=\"1\" />", "<a b.c=\"d\" />", "<a>&#1234567890;</a>", "<a>&#x10FFFF;</a>",
	"<a></a\n>", "<a></a >", "<a b=\" \" />", "<a> </a>", "<A>{<B />}</A>", "<></>< />",
	// Comments, whitespace and hashbangs
	"/* a */ b", "// a\nb", "a /* unterminated", "a // line", "#!hash\n1", "#!only", " a", "﻿a",
	"a b", "<!-- x", "a --> b", "/**/a", "/*\n*/a", "a/**/", "/* */", "// only", "// x\n", "//",
	"/*", "/*/", "/*/ */a", "a /* b */ c", "a\n// b\nc", "\t\v\f a", "a b", "　a", "a​b",
	" ", "\n", "\r\n", " ", "#!\n", "#", "#a", "@", "\\", "\u0000", "a\u0000", "…", "a…",
	// await, yield and let
	"await a", "await", "await\na", "async function f() { await }", "function f() { await a }",
	"function* f() { yield }", "yield a", "yield", "async () => await", "let", "let a", "let = 1",
	"let[a] = b", "(let) = 1", "let.a", "a[let]", "yield = 1", "await = 1", "(await) => 1",
	"async function f() { function g(await) {} }", "function* f() { function g(yield) {} }",
	"function* f() { (yield) => 1 }", "async function f() { (await 1) }", "async () => { var await }",
	// Branches the cases above leave unexercised
	'new {__proto__: a, "__proto__": b}', "new {__proto__: a, __proto__: b}",
	"({__proto__: 1, __proto__: 2, a: b = 1})", "({__proto__: x, __proto__: y, a: b = 1} = c)",
	'({1: a, 1n: b, 0x1: c, .5: d, [e]: f, "g": h})', "[(a + b), c]", "[(a + b), c] = d",
	"({a: (b + c), d})", "({a: (b + c), d} = e)", "[(a), b = 1]", "[...a,].b", "[[...a,].b] = c",
	"({a: {...b,}.c} = d)", "({...a, ...b, c})", "[...a, ...b, c]", "[...a, ...b, c] = d",
	"class { #x; m() { a + #x in b } }", "class { #x; m() { a < #x } }", "class { #x; m() { #x in a in b } }",
	"async function f() { await a; async(b) }", "async () => { await a; async(b) }",
	"function* g() { yield a; (b) }", "async function f() { await a; (b) }", "function* g() { yield a; async(b) }",
	"async function f() { await /a/g }", "async () => await /a/", "async () => await /[/u",
	u("%u0069mport(a)"), u("%u0069mport.meta"), u("n%u0065w.target"),
	"class A extends B { constructor() { new super() } }", "class A extends B { m() { new super.m() } }",
	"class A extends B { m() { new super() } }", "function f({...a, b}) {}", "function f({...a,}) {}",
	"({*a: 1})", "({async a: 1})", "({async *a: 1})", "({get a: 1})", "function f({a(){}}) {}",
	"function f({get a(){}}) {}", "new {a: 1}", "new {a}", "new {...a}", 'function f(a) { "use strict"; }',
	'(a) => { "use strict" }', "({m(a) { 'use strict' }})", "({get a(){}} = b)", "({set a(v){}}) => 1",
	"[a += 1] = b", "({a: b += 1} = c)", "[a ||= 1] = b", "((a)) => 1", "([(a)]) => 1", "({a: (b)}) => 1",
	"async ((a)) => 1", "(a.b) => 1", "async (a.b) => 1", "({a: b.c}) => 1", "([a.b]) => 1",
	"({a: (b.c)} = d)", "[(a.b)] = c", "/\\x4a/", "/\\u{1f600}/u", "/\\ua0b1/", "/(?=a/", "/(?<=a/",
	"/(?!a/", "/(?<!a/", "/{1}/", "/a|{1,2}/", "/({1})/", "/\\./u", "/\\[/u", "/\\//u", "/\\^\\$\\*/u",
	"/\\t\\n\\v\\f\\r/", "/[\\t\\n]/u", u("/%uD83D%u0041/u"), u("/%uD83Dx/u"), u("/%uD83D%uDE00/"),
	"/\\p{Script=}/u", "/\\p{Script=Latn/u", "/[\\z]/u", "/[\\c1]/u", "/[\\1]/u", "/[\\q{ab}a]/v",
	"/[[\\q{ab}]a]/v", "/[a\\q{bc}]/v", "/[z-a]/v", "/[a-z]/v", "/[[a]/v", "/[a[b/v", "/[\\n]/v",
	"/[\\x41]/v", "/[\\q{a]/v", "/[\\qa]/v", "/\\x41/", "/\\x41/u", "/\\123/", "/[\\123]/", "/\\400/",
	"(function: 1)", "a ? function : b", u("/a/%u0067"), "0x1z", "0b1a", "0o7x", "1na", "0nx",
	"tag`\\unicode${a}b`", "tag`\\u\r\nb`", "tag`\\u\\`b`", "tag`\\u", '"\\r\\b\\v\\f"', "// a\r\n",
	"/* a */ // b\r\n",
];

export const esm = [
	// Imports
	'import a from "b"', 'import {a} from "b"', 'import {a as b} from "c"', 'import * as a from "b"',
	'import a, {b} from "c"', 'import a, * as b from "c"', 'import "a"', 'import {} from "a"',
	'import {a,} from "b"', 'import {"a" as b} from "c"', 'import {"a"} from "b"', "import a from 'b';",
	'import a from "b"\nimport c from "d"', 'import a from "b"\nimport a from "c"', 'import {a, a} from "b"',
	'import a from "b" with {type: "json"}', 'import eval from "a"', 'import {if} from "a"',
	'import {if as x} from "a"', 'import yield from "a"', 'import let from "a"', 'import await from "a"',
	"import a from b", "import a", "import a from", "import(a)", "import.meta", 'import {a as if} from "b"',
	'import {default as a} from "b"', 'import {a as default} from "b"', 'import * from "a"',
	'import * as from "a"', 'import a, from "b"', 'import {a b} from "c"', 'import a "b"',
	"import 'a'\n'use strict'", 'import {\n  a,\n  b\n} from "c"', 'import a from "b";;',
	'import a from "b" // c', 'import a from "b" /* c */', 'import a from "b"; export {a}',
	'import {a as b, c as b} from "d"', 'import arguments from "a"', 'import {\\u0061} from "b"',
	'import \\u0061 from "b"', 'import {a as \\u0062} from "c"', 'import 𝒜 from "b"',
	'import "\\uD800"', 'import {"\\uD800" as a} from "b"', 'import a from "b"\nexport default a',
	// Exports
	"export const a = 1", "export let a = 1", "export var a", "export const a", "export const {a} = b",
	"export const [a, , b] = c", "export const {a: {b}, ...c} = d", "export function f() {}",
	"export async function f() {}", "export function* g() {}", "export class A {}", "export default 1",
	"export default function () {}", "export default function f() {}", "export default async function () {}",
	"export default class {}", "export default class A {}", "export default a = 1",
	"export default {a: 1}", "export {a}", "export {a as b}", "export {a as default}", 'export {a as "b c"}',
	'export {"a"} from "b"', 'export {"a" as b} from "c"', 'export {a} from "b"', 'export * from "a"',
	'export * as a from "b"', 'export * as "a b" from "c"', "export {a, a}", "export default 1\nexport default 2",
	"export const a = 1\nexport {a}", "export {if}", "export {a,}", "export {}", "export", "export const",
	"export {a", "export default", "export = 1", 'export {"\\uD800"} from "a"', "export {a as b, c as b}",
	"export const a = 1, b = 2", "export let a, b", "export const {a, a} = b", "export var [a] = b",
	"export var {a}", "export let [a]", "export function f() {}\nexport function f() {}",
	"export class A {}\nexport class A {}", "export default function f() {}\nexport {f}",
	"export default async () => {}", "export default async\nfunction f() {}", "export async\nfunction f() {}",
	"export async () => {}", "export class {}", "export function () {}", "export function* () {}",
	"export default function* () {}", "export default class extends A {}", "export default (1)",
	"export default [1]", "export default a\nb", "export default a;b", "export default async",
	"export default let", "export let", "export let\na = 1", "export let {a} = b", "export let [a] = b",
	"export var a = 1;\nexport var a = 2", "export {a}; var a", "export {a}\nexport const a = 1",
	"export {a as b}; let a", "export {arguments}", "export {eval}", "export {let}", "export {await}",
	'export {a} from "b"\nexport {a} from "c"', 'export * from "a"\nexport * from "b"',
	'export * as a from "b"\nexport * as a from "c"', "export default from", 'export {default} from "a"',
	'export {default as a} from "b"', 'export * as default from "a"', "export {a as\ndefault}",
	'export {"a"}', 'export {"a" as b}', 'export {a as "b"}; let a', "export const a = 1;",
	"export const a = 1;;", "export const a = 1 // c", "export const a = /* b */ 1",
	"export const a = 1\n\n", "export const a = <div />", "export const a = (\n  <div>\n    {b}\n  </div>\n)",
	"export const a = () => <b c={d} />", "export const a = `\n${b}\n`", "export const a = /re/g",
	'export const a = "use strict"', "export {\\u0061}; let a", "export {a as \\u0062}; let a",
	// Blocks with bodies
	'import a from "b"\nexport const c = a',
	'export const meta = {\n  title: "x",\n  tags: ["a", "b"]\n}',
	'export function Layout({children}) {\n  return <div className="x">{children}</div>\n}',
	"export const Chart = () => {\n  const data = [1, 2, 3]\n  return <ul>{data.map((d) => <li key={d}>{d}</li>)}</ul>\n}",
	"export function f() {\n  if (a) { b() } else if (c) d()\n  else { e }\n}",
	"export function f() {\n  for (let i = 0; i < 1; i++) {}\n  for (const a in b) {}\n  for (const a of b) {}\n  for (;;) break\n}",
	"export async function f() { for await (const a of b) {} }", "export function f() { for await (a of b) {} }",
	"export function f() { for (a in b) {} for (a of b) {} for (a.b of c) {} for ([a] of b) {} for ({a} of b) {} }",
	"export function f() { for (var a = 1 in b) {} }", "export function f() { for (let a = 1 of b) {} }",
	"export function f() { for (let of of a) {} }", "export function f() { for (let in a) {} }",
	"export function f() { for (async of a) {} }", "export function f() { for (async.x of a) {} }",
	"export function f() { for (let.x in a) {} }", "export function f() { for (let a, b of c) {} }",
	"export function f() { for (a = 1 of b) {} }", "export function f() { for ((a) of b) {} }",
	"export function f() { for (const a;;) {} }", "export function f() { for (const [a];;) {} }",
	"export async function f() { for await (;;) {} }", "export async function f() { for await (a in b) {} }",
	"export async function f() { for await (const a in b) {} }", "export function f() { for (x of a, b) {} }",
	"export function f() { for (x in a, b) {} }", "export function f() { for (a ? b : c in d;;) {} }",
	"export function f() { for (\"a\" in b;;) {} }", "export function f() { for ((a in b);;) {} }",
	"export function f() {\n  while (a) { continue }\n  do { break } while (b)\n  do x; while (y) z\n}",
	"export function f() {\n  switch (a) {\n    case 1:\n      b()\n      break\n    default:\n      c()\n  }\n}",
	"export function f() { switch (a) { case 1: default: default: } }", "export function f() { switch (a) { b() } }",
	"export function f() { switch (a) { case 1: let b; case 2: let b } }",
	"export function f() { switch (a) { case 1: function b() {} } }",
	"export function f() {\n  try { a() } catch (e) { b(e) } finally { c() }\n  try {} catch {}\n  try {} finally {}\n}",
	"export function f() { try {} }", "export function f() { try {} catch (e) { var e } }",
	"export function f() { try {} catch ([e]) { var e } }", "export function f() { try {} catch (e) { let e } }",
	"export function f() { try {} catch ({a, a}) {} }", "export function f() { try {} catch (e, f) {} }",
	"export function f() { throw a }", "export function f() { throw\na }", "export function f() { throw }",
	"export function f() { return\n1 }", "export function f() { return; }", "export function f() { l: for (;;) { continue l } }",
	"export function f() { l: l: ; }", "export function f() { break }", "export function f() { for(;;) break }",
	"export function f() { continue }", "export function f() { l: { break l } }", "export function f() { l: { continue l } }",
	"export function f() { a: b: while (1) continue a }", "export function f() { a: { b: { break a } } }",
	"export function f() { a: function g() {} }", "export function f() { if (a) function g() {} }",
	"export function f() { if (a) class B {} }", "export function f() { if (a) let b = 1 }",
	"export function f() { if (a) const b = 1 }", "export function f() { if (a) var b = 1 }",
	"export function f() { while (a) async function g() {} }", "export function f() { let a; var a }",
	"export function f() { var a; let a }", "export function f(a) { let a }", "export function f(a) { var a }",
	"export function f() { { function g() {} var g } }", "export function f() { function g() {} var g }",
	"export function f() { let a; { var a } }", "export function f() { const a = 1; function a() {} }",
	"export function f() { class A {} class A {} }", "export function f() { let let = 1 }",
	"export function f() { var let = 1 }", "export function f() { const {a, a} = b }",
	"export function f() { 'use strict'; 010 }", "export function f() { debugger }", "export function f() { with (a) {} }",
	"export function f() { ;;; }", "export function f() { {} }", "export function f() { a\n++b }",
	"export function f() { var a = 1, b }", "export function f() { var }", "export function f() { var a, }",
	"export function f() { let [a] }", "export function f() { var {a} }", "export function f() { let a = 1, [b] = c }",
	"export function f() { const a = 1, b }", "export function f() { class A extends B { constructor() { super(); super.x } } }",
	"export function f() { return function* () { yield; yield* a; yield\na } }",
	"export function f() { return async function () { await a; for await (b of c); } }",
	"export function f() { arguments; eval }", "export function f() { arguments = 1 }", "export function f() { eval = 1 }",
	"export function f() { var arguments }", "export function f() { function arguments() {} }",
	"export function f() { a = function eval() {} }", "export function f() { (function arguments() {}) }",
	"export function f() { return () => { new.target } }", "export function f() { return a => super.b }",
	"export function f() { import('a') }", "export function f() { import a from 'b' }",
	"export function f() { export const a = 1 }", "export function f() { new.target; }",
	"export function f(a = 1, {b}, [c], ...d) {}", "export function f(...a, b) {}", "export function f(...a = 1) {}",
	"export function f(...[a]) {}", "export function f(a,) {}", "export function f(,) {}", "export function f(a, a) {}",
	"export function f({a}, a) {}", "export function f([a, a]) {}", "export function f(a = b, b) {}",
	"export function f(a = await 1) {}", "export async function f(a = await 1) {}",
	"export function* f(a = yield) {}", "export function f(eval) {}", "export function f(arguments) {}",
	"export function f(a) { 'use strict' }", "export function f(a = 1) { 'use strict' }",
	"export function f({a}) { \"use strict\" }", "export function f(...a) { 'use\\x20strict' }",
	"export function f(a = 1) { ('use strict') }", "export function f(a = 1) { 'a'; 'use strict' }",
	"export function f(a = 1) { 'use strict'\n+ 1 }", "export function f(a = 1) { 'use strict'\n(1) }",
	"export function f(a = 1) { 'use strict'; }", "export function f(a = 1) { 'use strict' }",
	"export function f(a = 1) { 'use strict'\n}", "export function f(a = 1) { 'use strict'\na }",
	"export function f(a = 1) { 'use strict'\n!= 1 }", "export function f(a = 1) { 'use strict'\n! 1 }",
	"export class A {\n  #x = 1\n  static y = 2\n  get x() { return this.#x }\n  static { this.y++ }\n}",
	"export class A { m() { class B { n() { this.#x } } } }", "export class A { #x; m() { class B { n() { this.#x } } } }",
	"export class A { m() { class B { #x } this.#x } }", "export default class { #a; static #b; m() { return this.#a + A.#b } }",
	// Not ESM
	"const a = 1", "a", ";", "if (a) {}", "export const a = 1;\nconsole.log(a)", "{}", "function f() {}",
	"class A {}", "let a", "a: 1", "debugger", "throw a", "return", "await a", "'use strict'",
	"export const a = 1\nfunction f() {}", "import a from 'b'\n\na", "export {a}\nconst a = 1",
	// Hashbang and comments
	"#!x\nexport const a = 1", "// a\nexport const b = 1", "/* a */ export const b = 1", "/* ",
	"export const a = 1 /*", "export const a = `", "export const a = '", "export const a = \"\n\"",
	"export const a = 1\n// trailing", "export /* a */ const /* b */ c = 1",
	"<!-- a\nexport const b = 1", "export const a = 1\n--> b",
	// Branches the cases above leave unexercised
	u("export function f() { let a%u0062 = 1; }"), "export function f() { for(;;) break 1 }",
	"export function f() { for(;;) continue 'a' }", "export function f() { a: { break a; } }",
	"export function f() { a: for(;;) { continue a; } }", "export function f() { a: { continue a; } }",
	"export function f() { for (async of x); }", "export async function f() { for await (async of x); }",
	"export function f() { for (async of => 1;;); }", "export async function f() { for await (async x => x of y); }",
	u("export async function f() { for await (async o%u0066 x); }"), "export function f() { for (async.a of x); }",
	"export async function f() { for await (a in b); }", "export async function f() { for await (let a;;); }",
	"export async function f() { for await (a;;); }", "export async function f() { for await (;;); }",
	"export function f() { a: switch (b) { case 1: break a; } }",
	"export function f() { a: switch (b) { case 1: continue a; } }", "export const [a = 1] = b",
	"export const {a = 1} = b", "export let {a: [b = 1]} = c", "export const [a = 1] = b; export {a}",
	'import {a} from "c"\nexport {a as "b"}', 'export {"a" as b} from "c"', 'import {"a" as b} from "c"',
	'export * as "a" from "b"', "export {a}; export {a as b}", "export {a, b}\nexport {a as c}",
	"export {a as b, a as c}", "export function* g() { yield\n{} }", "export function f() { return\n{} }",
	"export function f() { for (async\nof x); }", "export async function f() { for await (async\nof x); }",
];

/** Names bound by earlier blocks for the import-prefix cases. */
export const importPrefixes = [["Thing"], ["a", "b"], ["a"]];

/** ESM blocks checked with earlier imports in scope. */
export const esmWithImports = [
	"export {Thing}", "export {a, b}", 'import Thing from "pkg"', 'import {a} from "b"', "export {c}",
	"export const x = a + b", "export default Thing", "export {a as default}", 'import b from "c"',
	"var a", "export var a", "export let a", "export function a() {}", "export class Thing {}",
];
